- README.md
- jwt.js
- package.json
- test.js
Ref #8 
Pretty much a new api with this PR. My brain needs a break but tomorrow I'll update tests as well as the readme.
> complete rebuild

- jwt.js
- package.json
- test.js
Fixes #22
cc @davidmarkclements @delvedor
> Use status code 401 for missing headers and code 400 for bad format

- README.md
Examples should suggest using `preValidation` since it is a better approach
> Update examples to use onRequest hook

- index.d.ts
- package.json
- tsconfig.json
- type.test.ts
Closes #37 
Not all completed.
> Add a typescript type definition file.

- README.md
Working example.
Fill the https://github.com/fastify/fastify-jwt/issues/38 issue.
> Change life cycle function's name to fit fastify v2 changes.

- .gitignore
- jwt.js
- package.json
- test.js
> chore(package): update standard to version 14.0.2

- index.d.ts
- type.test.ts
> Add typings for messages option

- README.md
- index.d.ts
- jwt.js
- test.js
- type.test.ts
> feat: add support for black-listing tokens

- index.d.ts
- type.test.ts
Added the user property to the FastifyRequest object, which is the payload provided to creating the token.
> fix: add user to FastifyRequest typings (#74)

- index.d.ts
- type.test.ts
Added missing cookie option from FastifyJWTOptions
> fix(): mising cookie option in FastifyJWTOptions

- README.md
- index.d.ts
- jwt.js
- test.js
- type.test.ts
> v1: Add ability to customise verification token

- README.md
> Typo on README.md.

- jwt.d.ts
- jwt.test-d.ts
Related to #96 and #98 
cc: @Ethan-Arrowood 
feel free to close
> namespace JWTTypes as individual

- jwt.d.ts
- jwt.test-d.ts
> Fix FastifyJWTOptions.secret property type

- index.d.ts
> FastifyJWTOptions.secret type fixed for 1.x

- package.json
- test.js
> Add additional tests to reach 100% code coverage

- README.md
validateToken function should return true when the decoded token is not included in blacklist
> docs: correct example of trusted tokens

- package.json
Resolve: #127
add pre-commit to ensure code is well tested before commit
> chore: :heavy_plus_sign: add pre-commit (#127)

- jwt.js
Resolve: #123 
Simple fix
No test case needed
> fix: missing request decorator user (#123)

- README.md
- jwt.d.ts
- jwt.js
- jwt.test-d.ts
- test.js
Closes #130.  Please let me know if there's anything I should correct.
> Add `formatUser` option.

- README.md
Closes #132
Updated the readme to include usage with verifying with JWKS
> add jwks usage to readme

- README.md
- jwt.js
- test/test.js
> Avoid to expose secret in jwt object

- jwt.d.ts
- jwt.test-d.ts
- test/test.js
> Fix 'cookie' and 'secret' types

- README.md
Spent a while figuring out that in order to augment a module, you had to actually import the module first for TypeScript to merge both declarations.
If the import is omitted, TypeScript will actually overwrite the existing module.
Hence I propose a slight improvement in the README to make it friendlier for TypeScript newcomers.
> Improved README for module augmentation

- README.md
Including it in the documentation, will help typescript developers save their time.
> Update README, Typescript Custom Type Declaration

- README.md
> docs: update Authentication for some routes example to use the  onRequest hook

- package.json
- test/jwt.test.js
> build(deps-dev): use new @fastify org dependencies

- README.md
- UPGRADING.md
- example/UsingCertificates.md
See https://github.com/fastify/fastify/issues/3733
> docs: update references to old fastify-* modules

- jwt.d.ts
> docs: fix jwt type usage documentation

- jwt.js
- package.json
> replace http-errors with @fastify/errors

- jwt.d.ts
- test/types/jwt.test-d.ts
> chore: add missing lookupToken to the type

- package.json
- test/jwt.test.js
> bump fast-jwt to get support for Node 18

- package.json
> run lint on pre-commit

- package.json
> remove dev dependency typescript
