jwt.js
~~solves: #5 #4~~ 
Adds `name` property to plugin-meta. see: https://github.com/fastify/fastify-plugin/issues/17#issuecomment-355972265
=> Adds name property to plugin-meta

README.md, jwt.js, test.js
Address this feature proposal : https://github.com/fastify/fastify-jwt/issues/27#issue-373060330
Currently i have already done this:
What needs to be done :
Concerning the `algorithm` prefix do you think it's really worth doing it ? (I already have a commit ready if needed)
IMO it's the better way to transition through the actual `0.6.0` version and the `0.8.0` or `0.9.0` versions (if we consider this PR will land with the version `0.7.0`) and thus giving users the time they need to adopt the new recommended options management.
=> Options management support

jwt.js, test.js
Previously you'd get an "Internal Server Error" which sounds like it's the server's fault and out of the user's control, but an expired token is actually actionable for users
=> Respond with 401 instead of 500 if token is expired

jwt.js, test.js
"internal server error" is not really accurate for an invalid/malformed token. having an invalid token is something users can normally solve (just get a new one), so 401 seems more appropriate
=> Return 401 for all invalid tokens

README.md
Previously, the example is not working if user copied directly because:
- User needs to install `request` module with `npm i --save request`
- Missing:
```
const jwt = require('fastify-jwt')
const request = require('request')
```
- `token` property of undefined `sign` variable
- body variable does not have bar property
=> Fix not working example in README

jwt.js, test.js
Hi!
While moving one of my projects from Express to Fastify I noticed `fastify-jwt` doesn't handle `Buffer` objects passed as `options.secret` in a correct way, causing JWT verification attempts to fail. I'm working with a Twitch.tv extension and it [expects me to verify tokens with Buffer objects](https://discuss.dev.twitch.tv/t/invalid-signature-attempting-to-verify-token-node-js/12146). I was able to do it with `jsonwebtoken` and `Buffer.from(...)`, but `fastify-jwt` throws `Error('missing private key and/or public key')`.
I made a quick fix that causes the project to pass `Buffer` objects directly to `secretOrPublicKey` variable, making it possible to successfuly verify JWTs in cases like the one I described above.
~~Alternatively, `!Buffer.isBuffer(secret)` can also be used as a …
=> fix for passing Buffer object as secretOrPublicKey

jwt.js, test.js
Currently, if token verification fails inside `request.jwtVerify(options, callback)`, then `callback` winds up being invoked twice -- first with an error, and then without.
This appears to be due to a missing else clause (or a missing return statement) in the callback at the end of `requestVerify()` (currently lines 224-228 of jwt.js).
The fix is pretty simple; not sure if a test ought to be written for this, but happy to do so if needed.
=> Fix double-invocation of callback in requestVerify

package.json
I was able to fix the issue #50 by installing @types/jsonwebtoken as a dependency instead of a devDep. This makes sense as if you're shipping the `index.d.ts` and it is referencing types from `@types/jsonwebtoken` then you should be shipping those types with the package.
=> Move @types/jsonwebtoken to dep list

index.d.ts, type.test.ts
The latest type definitions is invalid to pass `sign` / `verify` / `decode` options.
And, `reply.jwtSign` isn't defined yet.
This PR rewrites type definitions for usability.
=> Refactor type definitions

index.d.ts, type.test.ts
Since the doc states that it's allowed to provide a public/private keys,
the typescript definitions should also support that.
Closes #60
=> Add public/private object shape to the FastifyJWTOptions' secret prop

README.md, jwt.js, test.js
Custom messages for HTTP responses to be passed as additional options. User can choose custom messages the rest will fallback to default. As discussed at #62.
```js
const fastify = require('fastify')
const myCustomMessages = {
badRequestErrorMessage: 'Bad Request: Header Missing',
// noAuthorizationInHeaderMessage and authorizationTokenExpiredMessage will fallback to default
// for the below message you can pass either a function as shown or a string
authorizationTokenInvalid: (err) => `error: ${err.message}`
}
fastify.register(require('fastify-jwt'), {
secret: 'supersecret',
messages: myCustomMessages
})
```
=> [Feature] allow custom HTTP response messages

README.md
Hi!
I've created this plugin based on top of fastify-jwt that enables verification of Auth0 issued tokens with HS256 or RS256.
Hope this helps!
Fixes #72
=> Add link to fastify-auth0-verify

README.md
There seems to be an error in the README. When `secret` is a function, the second parameter is a decoded token, not `reply`.
=> Error: Change `reply` to `token`

README.md, jwt.js, package.json, test.js
- refs:  fastify/fastify-jwt#80
This aims to add cookie support to the current `req.jwtVerify` decorator. Generally JSON web tokens are assumed (and correctly so) to be included in the `Authorization` header as part of bearer authentication. JWT's are also meant to be short term since they are stateless, however in a lot of situations one would want to persist the token on the front-end so that they can attach the token to every request to the backend.
The frontend will then persist the token in usually in localstorage or some state store (redux/vuex). However for best security practices, one would want to store the token in a properly configured cookie (httpOnly + sameSite + secure) which will prevent any `js` from reading the token reducing the attack surface.
This feature will …
=> feature: add cookie option to req verify decorator

README.md
The two first examples in the README has a small error in it causing them to throw if they are cut and pasted:
```sh
fastify.register(require('fastify-jwt'), {
^
TypeError: fastify.register is not a function
```
This fixes it.
=> Two first examples in the README is not working

README.md, jwt.d.ts, jwt.js, jwt.test-d.ts, test.js
Fixes #90 Add ability to specify the token location in request headers
=> Add ability to specify the token location in request headers

jwt.d.ts, package.json
This PR updates typings to follow the rename in the main `fastify` project.
Hopefully closes #94
=> align typings with latest fastify version

.gitignore, README.md, jwt.d.ts, jwt.test-d.ts
=> feat(types): support define custom payload

README.md
Add the `module` keyword to the declaration merging snippet in the TS section in the README file
=> 📝Fix TS snippet in the docs by adding the module keyword

README.md, jwt.d.ts, jwt.js, jwt.test-d.ts, test.js
Support `secret` option as a function returning a promise or an async function.
Note that the typescript types are quite off already and they're not testing much as far as the secret function is concerned. I'm not using typescript so I have not fixed them, but for example the parameters provided to the pre-existing `secret` provided as a function are already wrong, i.e. the second argument is not the Reply but rather the decoded token. **I did not fix this**.
Supersedes https://github.com/fastify/fastify-jwt/pull/140 and closes https://github.com/fastify/fastify-jwt/issues/139
=> feat: support promise/async secret function

README.md, jwt.d.ts, jwt.js, jwt.test-d.ts, test/test.js
Closes #151 
This PR adds the ability to verify a JWT from `fastify-cookie` when the cookie is signed with a secret. 
=> feat: Verify JWT from a signed cookie

example/UsingCertificates.md, test/helper.js
Hello.
* Fixes tests by generating an `ES256` (used curve: `prime256v1`) key pair, using a `secp256k1` curve generates an `ES256K` key pair (currently not supported by `jsonwebtoken` or `fast-jwt` in the upcoming release).
* Updates the related documentation.
For reference: [rfc8812 - section 3.2](https://datatracker.ietf.org/doc/html/rfc8812#section-3.2).
=> fix: ECDSA key pair generation and related documentation

jwt.d.ts
Removed duplicate method overloads that were unreachable, as the compiler always resolves calls to the textually first matching overload.
=> refactor(definitions): remove duplicate method overloads

jwt.d.ts, package.json, test/jwt.test.js
As mentioned in #188, this PR removes the JwtHeader type definition from this repository and uses the one from [fast-jwt](https://github.com/nearform/fast-jwt/blob/eff9cfeb0d7e2b24d04c1b37f7870447f4881eb1/src/index.d.ts#L56).
The PR needs to be updated once https://github.com/nearform/fast-jwt/issues/155 is released as it is currently pointing to the master branch.
Closes #188 
=> chore: Remove JwtHeader type definition

jwt.d.ts, test/jwt.test.js, test/types/jwt.test-d.ts
Instead of just a string, the secret returned from the callback/promise can also be a Buffer
=> secret function can also return a Buffer as type

jwt.d.ts, test/jwt.test.js
Implementation of this plugin doesn't support named imports. That is why `jwt.d.ts` has been actualized. 
Closes #150 
=> chore: remove named export of fastifyJwt

jwt.js, test/jwt.test.js
When using reply.jwtSign without a callback convertTemporealProps gets called two times multiplying time props twice incorrectly.
- move the check for the callback before the call to convertTemporalProps, so they are not called twice
- add assertions checking token exp prop to existing time definitions tests
Closes #207
=> fix: reply.jwtSign sets wrong exp

jwt.js, package.json, test/jwt.test.js
Hello.
This PR aims to :
- upgrade package dependencies
- avoid initial options mutation and return the original options to the user through the `fastify.jwt.options` decorator property (fix https://github.com/fastify/fastify-jwt/issues/213)
=> fix: do not mutate and return the initial options

jwt.js, package.json, test/jwt.test.js
=> Updated to Fastify v4

README.md, jwt.js, test/jwt.test.js
Changed decorator name to avoid conflict with @fastify/passport plugin using the same decorator
=> Change decorator name

jwt.js, test/jwt.test.js
Replaced a line missed in pull https://github.com/fastify/fastify-jwt/pull/229 , where the old `request.user` was still used, with the new decoratorName variable 
=> Add decoratorName in the request object instead of default user

jwt.d.ts, test/types/jwt.test-d.ts
Add new type definition to support ES256 with passphrase in TypeScript.
Closes #246 
=> fix: add type to support ES256 with passphrase in TypeScript

jwt.d.ts, test/jwt.test.js, test/types/jwt.test-d.ts
Fork of https://github.com/fastify/fastify-jwt/pull/263 with added type test
Closes https://github.com/fastify/fastify-jwt/pull/263 and https://github.com/fastify/fastify-jwt/pull/260
=> Add `onlyCookie` verify option tests and types
